import { Service } from "./types";

export const services: Service[] = [
  {
    id: "wordpress-development",
    slug: "wordpress-development",
    title: "WordPress Development",
    description:
      "Custom themes, plugin configuration, and responsive builds — no page builders unless the project calls for it.",
    whatItIncludes: [
      "Custom theme development (no generic templates)",
      "Plugin selection, configuration, and customisation",
      "Performance optimisation — fast load times, clean code",
      "Responsive design — tested on mobile, tablet, and desktop",
      "Content management setup so you can edit your own site",
    ],
    idealClients:
      "Small businesses, service providers, and professionals who need a serious website built properly — not a template they could have set up themselves.",
    deliverables: ["Live website", "Source files", "Basic CMS training", "Deployment support"],
  },
  {
    id: "frontend-development",
    slug: "frontend-development",
    title: "Frontend Development",
    description:
      "Clean HTML, CSS, and JavaScript. Mobile-first layouts that work across every device and screen size.",
    whatItIncludes: [
      "HTML, CSS, and JavaScript — written by hand, not generated by a drag-and-drop builder",
      "Mobile-first layouts, built to work on every screen size",
      "Accessible, semantic markup — the kind that search engines and screen readers can understand",
      "Integration with WordPress themes or standalone static builds",
    ],
    idealClients:
      "Businesses that need a custom frontend experience, developers who need a reliable collaborator, or anyone who wants a website built to a standard rather than a speed.",
    deliverables: ["Fully coded pages", "Responsive implementation", "Clean, commented code"],
  },
  {
    id: "woocommerce-development",
    slug: "woocommerce-development",
    title: "WooCommerce Development",
    description: "Full e-commerce builds — product catalogues, checkout flows, and payment integration.",
    whatItIncludes: [
      "Full store setup — products, categories, variations, and pricing",
      "Checkout and payment gateway integration",
      "Custom CSS and layout adjustments beyond WooCommerce defaults",
      "Product management training so you can run your own store",
      "Compatibility with existing WordPress sites or fresh builds",
    ],
    idealClients:
      "Retailers, pharmacies, specialists, and any business that needs to sell online with a proper storefront — not a generic hosted shop.",
    deliverables: ["Live store", "Payment integration", "Admin training", "Deployment support"],
  },
  {
    id: "website-optimisation",
    slug: "website-optimisation",
    title: "Website Optimisation",
    description:
      "Performance audits, image compression, and cleanup to make your existing site faster and more efficient.",
    whatItIncludes: [
      "Performance audit — identifying what's slowing your site down",
      "Image compression and lazy loading",
      "CSS and JavaScript cleanup — removing unused code",
      "Caching configuration for faster repeat visits",
      "Mobile performance improvements",
    ],
    idealClients:
      "Businesses with an existing website that loads slowly, ranks poorly, or doesn't perform well on mobile. You don't need a new website — you need the one you have to work properly.",
    deliverables: ["Audit report", "Implemented improvements", "Before/after performance metrics"],
  },
  {
    id: "ai-assisted-development",
    slug: "ai-assisted-development",
    title: "AI-Assisted Development",
    description: "Using Claude and ChatGPT as professional workflow tools to build faster without sacrificing code quality.",
    whatItIncludes: [
      "Faster build times without compromising quality — AI accelerates the workflow, not the standards",
      "Complex animation sequences and custom interactions",
      "Rapid prototyping and iteration on layout and functionality",
      "All AI-generated code reviewed, tested, and refined to production quality",
    ],
    idealClients: "Any project where speed and budget matter — which is most projects.",
    deliverables: [
      "Same as the relevant primary service — this approach is part of the workflow, not a separate product.",
    ],
    benefits:
      "I use Claude and ChatGPT as professional workflow tools. This is not \"an AI built my website.\" It is: I directed an AI to generate structural code, reviewed everything it produced, fixed what needed fixing, and took responsibility for the result. The outcome is faster, more thorough development — the same quality bar, reached in less time.",
  },
];

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find((service) => service.slug === slug);
}
